### ISSUE TITLE
Hello, I tried to download the file : http://datino.isti.cnr.it/tern/data.tar, but failed

### ISSUE THREAD

**Issue by zhanghehe8** [mesnico/TERN#10]
Hello, I tried to download the file : http://datino.isti.cnr.it/tern/data.tar, but failed

**Comment by mesnico** [comment]
Hi @zhanghehe8, unfortunately we are having problems with our network storage. We are working to solve the problem. Hopefully the link will work again in the next days, sorry about that.

**Comment by zhanghehe8** [comment]
I see. Thank you for your reply

**Comment by mesnico** [comment]
While waiting for the network storage to work again, I temporarily uploaded the files to Google Drive. 
Here is the link: https://drive.google.com/drive/folders/1njEa9t7TXRX6GIbj31LUu4cCDx_sImzK?usp=sharing

I also updated the readme with this temporary link.

**Comment by aaaa7788** [comment]
hi @mesnico , thanks for your effort. Can you also upload the data and models used in TERAN? Links failed too.

**Comment by mesnico** [comment]
@aaaa7788 I uploaded the models and data for TERAN to the same link. Notice that the features_36.tar containing the image features from COCO should work for both TERN and TERAN. Unfortunately, I am not able to upload the pre-extracted features on Flickr-30k used in TERAN, as I have almost exhausted the available space on Google Drive. We hope to solve our NAS problem as soon as possible

**Comment by mesnico** [comment]
@aaaa7788 I was able to make some space in the current account, and I uploaded also the Flickr-30k features, inside the TERAN folder.

**Comment by aaaa7788** [comment]
@mesnico  Thank you so much !!

**Comment by AuTheConder** [comment]
@mesnico Hello, the links had failed again. Can you please update the links again？I will so appreciate it！

**Comment by mesnico** [comment]
@AuTheConder sorry for the inconvenience and for the delay.
I relayed the files on [OneDrive](https://cnrsc-my.sharepoint.com/:f:/g/personal/nicola_messina_cnr_it/EnsuSFo-rG5Pmf2FhQDPe7EBCHrNtR1ujSIOEcgaj5Xrwg?e=Ger6Sl).
I also updated the README accordingly.

Let me know if you find any problems.
