### ISSUE TITLE
Data download failure

### ISSUE THREAD

**Issue by Daydaylight** [mesnico/TERN#13]
Hi, I'm trying to download the data from the link you gave me, but neither link can be opened.
I would appreciate it if you told me how to solve it.

**Comment by mesnico** [comment]
Hi @Daydaylight, you should use the google drive link reported in the README to download the data, as our NAS had problems and is still offline.
https://drive.google.com/drive/folders/17rZmJJdFQyRFHCn1PIEJT8HO6_Bj0Imi?usp=sharing
