### ISSUE TITLE
model_best_ndcg.pth.tar cannot be opened

### ISSUE THREAD

**Issue by MauritsBleeker** [mesnico/TERN#14]
Hi,

I downloaded model_best_ndcg.pth.tar from Drive, to test the model. 
However, the tar file seems to be corrupted, since it is not a valid tar file that can be opened.
I get the following error 
`: Error opening archive: Failed to open 'model_best_ndcg.pth.tar'` 
Would it be possible to share a valid tar file?

Thanks,
Maurits

**Comment by MauritsBleeker** [comment]
Okay, the problem is solved already. 
model_best_ndcg.pth.tar is not a tar file in the first place, but a torch checkpoint.

**Comment by huanhugu** [comment]
how to solve please?
