### ISSUE TITLE
Eval code clarification

### ISSUE THREAD

**Issue by AmeenAli** [mesnico/TERN#2]
Hello <br>
I have noticed in the following function : <br>
https://github.com/mesnico/TERN/blob/e147f8369ac80b71f77649f282fa92c7193263c1/evaluation.py#L197
<br>
you are doing everything shifted by 5, would love to know why.
Thanks!

**Comment by mesnico** [comment]
Hi @AmeenAli,
the evaluation code is from [VSE++](https://github.com/fartashf/vsepp). Basically, in MSCOCO there are 5 captions for each image. When the features are loaded, there is some image feature redundancy (every image is repeated for every one of its 5 captions). For this reason, if we want to consider every image feature once, we have to sample from the image feature list once every 5. 
Hope it helps
