### ISSUE TITLE
MultiGPU training

### ISSUE THREAD

**Issue by AmeenAli** [mesnico/TERN#3]
Hello.
is there any option for multiGPU training?
Thanks

**Comment by mesnico** [comment]
Hi @AmeenAli , as of now multi-GPU is not supported. However, it is not difficult in PyTorch to enable multi-GPU: have a look at [torch.nn.DataParallel](https://pytorch.org/docs/master/generated/torch.nn.DataParallel.html)

**Comment by Lavrikov** [comment]
Hi,  i have a packages installation error
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement faiss-prebuilt==1.4
issue appears after that: conda env create --file environment.yml

**Comment by mesnico** [comment]
Hi @Lavrikov, I solved the issue: this package is not needed in the conda environment. You can pull and check if it works now.
Please open a new issue if you have further problems with packages, this is not the right topic for this issue.
