### ISSUE TITLE
Table 1.

### ISSUE THREAD

**Issue by AmeenAli** [mesnico/TERN#4]
Hello
the numbers in table 1 regarding the model VSRN are not the same as in VSRN table, can you clarify ?

**Comment by mesnico** [comment]
Hi @AmeenAli , I think you are asking why the values in Table 1 differ from the values reported by the VSRN authors. 
VSRN authors reported their results for an ensemble of 2 models. For a fair comparison, we rerun the experiments using only their best performing model.
